### PR TITLE
Replace Cowboy with Bandit

### PR DESCRIPTION
**Pull request by sergiofenoll**
Remove the Cowboy dependency and instantiate a [Bandit](https://github.com/mtrudel/bandit) plug instead of a Cowboy plug. According to the Bandit docs, it should in general be a drop-in replacement for Plug.Cowboy. Note that we don't pass a compress option to the Bandit plug because Bandit should enable compression by default according to [the docs](https://hexdocs.pm/bandit/Bandit.html).

:warning: **This requires a bump of the plug dependency in plug_mint_proxy!** See related PR below:
- https://github.com/madnificent/plug-mint-proxy/pull/2

Some context: the identifier (and dispatcher) currently use Cowboy to provide a HTTP server where clients can connect. While it works, it has some quirks w.r.t. [timing out ongoing requests](https://github.com/ninenines/cowboy/issues/1278). In Kaleidos we notice this when serving large files. Clients' downloads will abruptly end mid-stream because the identifier closes the connection due to Cowboy's behaviour. We can mitigate this by raising the `idle_timeout` setting of Cowboy, but there will always be a cut-off point for long lasting HTTP requests. Based on local testing, Bandit does not seem to have this behaviour.

### CODE REVIEW

**Comment by madnificent** [comment]
Hi @sergiofenoll, does this also need a counterpart in semtech/mu-dispatcher?

**Comment by madnificent** [comment]
@sergiofenoll Changes have been reverted and a feature branch `feature/gun` has been made with the current state.

Feel free to reopen the PR or suggest alternative approaches.  Currently open issue we noticed was responses with an empty response body not flowing to the frontend but we did not dig into the why of that.

**Comment by sergiofenoll** [comment]
@madnificent thanks for the heads up, sorry for the mishap, should've marked the PR as a draft. If I pick it up again I'll let you know.

**Comment by madnificent** [comment]
My bad.  You informed through another channel.  This PR is likely fairly close to something working and a good improvement.  It is not urgent from this end.  Thank you for the continued support :+1:

**Pull request merged**
